# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    OC\UserBundle\Entity\User: plaintext
  role_hierarchy:
           # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR,ROLE_USER]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    OC\UserBundle\Entity\User
        property: username

  firewalls:  
    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     %secret%
      
security:
    encoders:
        OC\UserBundle\Entity\User: sha512
    access_control:
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
    providers:
      main:
        id: fos_user.user_provider.username