services:
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    OC\UserBundle\DataFixtures\ORM\LoadUser:
        tags: [doctrine.fixture.orm]
